### PR TITLE
Updated APIs for JRuby 9000

### PR DESCRIPTION
**Pull request by jhstatewide**
Updated APIs for JRuby 9000

### CODE REVIEW

**Comment by kares** [comment]
hey, thanks! master is a [WiP](https://github.com/jruby/jruby-rack/issues/168) - originally not meant as 9K only, but than it depends who ever finished up :)

**Comment by jhstatewide** [comment]
I am actually not sure of the best option to support 1.6+1.7 at the same time as 9000... should there be a "jruby-rack-9000" gem as well? 2 jar files? Other java tricks? 

Since 9k is so new I am sure people will be using 1.7.xx for some time to come.

I am attempting to get Trinidad working perfectly on JRuby 9000, since it's a great platform but it did not work at all when I first tried it. Now that jruby-rack is (mostly) working I am hoping I can make a few adjustments to Trinidad to get the 9k support.

**Comment by kares** [comment]
well, in that case you're looking at the wrong parts ... there's a **1.1** branch.
also the `Arirty` API is deprecated but still there: https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/runtime/Arity.java#L53 ... thus I'm closing this one, for now

p.s. you could try trinidad from master and report what are your current issues in terms of compatibility.

**Comment by jhstatewide** [comment]
"p.s. you could try trinidad from master and report what are your current issues in terms of compatibility."

Will do -- last time I tried it I got some kind of ENUM undefined for RUBY2_2. I'll get the exact error to you.

**Comment by jhstatewide** [comment]
@kares https://github.com/trinidad/trinidad/issues/134

**Pull request closed without merging**
