### PR TITLE
Add Rack::Handler::Servlet::DefaultEnv#get_header

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
Fixes https://github.com/jruby/jruby-rack/issues/211

### CODE REVIEW

**Comment by kares** [comment]
thanks for getting sessions working, hopefully the rest of the code-base is compatible with Rails 5.x as well :)
guess its done as is or are you planning on adding tests?

**Comment by HarlemSquirrel** [comment]
I just bumped the rack version to 2.0.3 and everything is passing! I think that may be the best way to test it, no? 

Without my changes there are 3 failures:

```
Failures:

  1) Rack::Handler::Servlet (default) env behaves like env sets attributes with false/null values
     Failure/Error: expect( env['org.false'] ).to be false
       
       expected #<FalseClass:0> => false
            got #<String:5364> => ""
       
       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     Shared Example Group: "env" called from ./src/spec/ruby/rack/handler/servlet_spec.rb:819
     # ./src/spec/ruby/rack/handler/servlet_spec.rb:376:in `block in (root)'
     # org/jruby/RubyBasicObject.java:1691:in `instance_eval'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'

  2) Rack::Handler::Servlet lazy env behaves like env sets attributes with false/null values
     Failure/Error: expect( env['org.false'] ).to be false
       
       expected #<FalseClass:0> => false
            got #<String:5624> => ""
       
       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     Shared Example Group: "env" called from ./src/spec/ruby/rack/handler/servlet_spec.rb:835
     # ./src/spec/ruby/rack/handler/servlet_spec.rb:376:in `block in (root)'
     # org/jruby/RubyBasicObject.java:1691:in `instance_eval'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'

  3) Rack::Handler::Servlet servlet-env behaves like env sets attributes with false/null values
     Failure/Error: expect( env['org.false'] ).to be false
       
       expected #<FalseClass:0> => false
            got #<String:5886> => ""
       
       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     Shared Example Group: "env" called from ./src/spec/ruby/rack/handler/servlet_spec.rb:1000
     # ./src/spec/ruby/rack/handler/servlet_spec.rb:376:in `block in (root)'
     # org/jruby/RubyBasicObject.java:1691:in `instance_eval'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'
     # org/jruby/RubyArray.java:2486:in `map'

Finished in 44.82 seconds
581 examples, 3 failures, 2 pending
```

**Comment by kares** [comment]
OK, thanks. Yes the bump is a good preliminary test. 
Wasn't sure how well your changes are tested esp. in relation to the session store ...

However, for 1.1.x line we should not update the (bundled) rack version, unsure of Rack 2.0's details but tests are likely no where near testing it our for real on a servlet container. So the version bump should get reverted.

**Comment by HarlemSquirrel** [comment]
That makes sense. I've added a revert commit. All seems to be well with Rails 5.1.3 and JRuby 9.1.12.0 just so you know!

**Comment by kares** [comment]
looking good, thank you! 1.1 release hopefully next week or so ...

**Pull request merged**
